# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='num_classes',
            new_name='num_items',
        ),
    ]
