# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181002_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
