# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 21:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181008_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mark',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
