# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181010_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='required_mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
